### PR TITLE
Gh104 update sparql query iri

### LINKED ISSUE #104: Bad IRI in a SPARQL Query in MagmaCoreServiceQueries
Looks like one of the `semanticweb` IRIs was missed during the recent change. It's on line 550 in this file and causes the query to fail:

`core/src/main/java/uk/gov/gchq/magmacore/service/sparql/MagmaCoreServiceQueries.java`

### PR DESCRIPTION
**Pull request by twalmsley**
Fixes #104

### CODE REVIEW

File: core/src/main/java/uk/gov/gchq/magmacore/service/sparql/MagmaCoreServiceQueries.java [hunk 1]
```diff
@@ -547,7 +547,7 @@ public class MagmaCoreServiceQueries {
      * A partial search by sign for entities referenced by an Activity.
      */
     public static final String FIND_MEMBERS_OF_CLASS_BY_ACTIVITY_AND_PARTIAL_SIGN_CASE_SENSITIVE = """
-            PREFIX hqdm: <http://www.semanticweb.org/hqdm#>
```
Comment (GCHQDeveloper42) [inline core/src/main/java/uk/gov/gchq/magmacore/service/sparql/MagmaCoreServiceQueries.java:550]: Aghhh! we missed one!

**Review by GCHQDeveloper42 — APPROVED** [review]
